blank_issues_enabled: false
contact_links:
    - name: "Question"
      url: "https://github.com/spessasus/spessasynth_lib/discussions/new?category=q-a"
      about: "Something is unclear? Ask a question!"
    - name: "Documentation"
      url: "https://spessasus.github.io/spessasynth_lib/"
      about: "Visit the complete API documentation!"
    - name: "spessasynth_core Documentation"
      url: "https://spessasus.github.io/spessasynth_core/"
      about: "The documentation for the underlying spessasynth_core library."
