name: Publish the npm package

on:
    push:
        tags:
            - "v*"

    workflow_dispatch:

jobs:
    publish-npm:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: latest
                  registry-url: https://registry.npmjs.org

            - name: Install dependencies
              run: npm ci

            - name: Set up Python
              uses: actions/setup-python@v6

            - name: Install Zensical
              run: pip install zensical

            - name: Build and publish to npm registry
              run: npm publish --provenance --access public
